INSERT INTO ADMIN (USERNAME, PASSWORD) VALUES ('admin', 'admin123');

INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Ford', 667000, 'Gör dig redo att älska bilkörning igen! Helt nya Mustang Mach-E är helt elektrisk och en ny form av frihet, byggd på all den passion som dess ikoniska status rymmer. Nu tillgänglig för beställning hos din Fordåterförsäljare.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Ford Puma', 238000, 'En ny era av renare elhybridfordon är här och Ford Puma förkroppsligar denna nya riktning. Puma-motorerna erbjuder ett urval av nya framåtblickande, avancerade EcoBoost hybridbensinmotorer med enastående prestanda.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Ford Kuga', 480000, 'Ford Kuga kombinerar elegant stil och tuff kapacitet med förfinad modern design på utsidan och ett anpassningsbart mångsidigt utrymme på insidan. Finns med Fords senaste laddhybridteknik för en renare och tystare körning.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Kia Rio', 195000, 'Kia Rio är vår dynamiska halvkombi som inte bara har en attraktiv design: här får du även bra prestanda, rymlig kupé, generöst med utrustning samt hög säkerhet med flera moderna säkerhetssystem.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Kia Niro', 341000, 'Kia Niro har sedan lanseringen 2016 varit en av våra mest populära bilmodeller. Nu är helt nya Kia Niro beställningsbar och den nya bilen kombinerar hög teknisk nivå med utomordentlig användarvänlighet.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Kia Sportage', 454000, 'Kia Sportage är tillbaka och lanseras nu som Plug-In Hybrid, med en räckvidd upp till 70 km på el. Sportage är en rymlig, fyrhjulsdriven SUV, lämpad för såväl pulserande storstadskörning som äventyr ute i det fria.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Volvo V60', 582000, 'Tack vare sin banbrytande 800-voltsteknik kan nya Volvo V60 laddas från 10–80% på endast 18 minuter vid laddning på minst 240kW. En fulladdad EV6 ger en räckvidd på upp till 528 kilometer.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Volvo S90', 255000, 'Volvo S90 kombinerar elegant stil och tuff kapacitet med förfinad modern design på utsidan och ett anpassningsbart mångsidigt utrymme på insidan. Finns med Fords senaste laddhybridteknik för en renare och tystare körning.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Volvo C40', 183000, 'En ny era av renare elhybridfordon är här och Volvo C40 förkroppsligar denna nya riktning. Puma-motorerna erbjuder ett urval av nya framåtblickande, avancerade EcoBoost hybridbensinmotorer med enastående prestanda.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('Kia Picanto', 197000, 'Trots det lilla formatet bjuder Kia Picanto på modern teknik och komfort som inte hör till vanligheterna i den här klassen. Picanto har fina designdetaljer samt är otroligt flexibel. Med Kia Picanto får du en flexibilitet för din vardag, och dina äventyr.', 10);