INSERT INTO ADMIN (USERNAME, PASSWORD) VALUES ('admin', 'admin123');

INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM1', 191, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM2', 291, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM3', 391, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM4', 195, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM5', 131, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM6', 156, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM7', 295, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM8', 467, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM9', 591, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);
INSERT INTO PRODUCT (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ('ITEM10', 197, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi.', 10);