INSERT INTO ADMIN (USERNAME, PASSWORD) VALUES ("admin", "admin123");

INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM2", 191, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM3", 192, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM4", 193, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM5", 194, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM6", 195, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM7", 196, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM7", 197, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM8", 198, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM9", 199, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)
INSERT INTO ITEM (NAME, PRICE, DESCRIPTION, QUANTITY) VALUES ("ITEM10", 200, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sit amet molestie ligula. Integer at nulla luctus, vehicula augue ut, semper tortor. Pellentesque eu luctus nisi. Nulla posuere auctor metus, ornare sagittis enim tempus vitae mauris.", 10)