CREATE TABLE ADMIN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(25),
    PASSWORD VARCHAR(25)
);

CREATE TABLE PRODUCT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25),
    PRICE BIGINT NOT NULL,
    DESCRIPTION VARCHAR(250),
    QUANTITY BIGINT
);