 CREATE TABLE ADMIN (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(25),
    PASSWORD VARCHAR(25)
);

CREATE TABLE PRODUCT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE BIGINT NOT NULL,
    DESCRIPTION VARCHAR(500),
    QUANTITY BIGINT
);
